name: Commit Lint

on:
  pull_request:
    types: [closed]
    branches:
        - main
  workflow_dispatch:

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json 